### ISSUE TITLE
SignUp endpoint not Saving all details sent in Body

### ISSUE THREAD

**Issue by adityavinodk** [aniketnk/alcoding-data-analysis#29]
The signUp endpoint doesn't store all details like USN which aren't in the User model. Hence we need a different approach to save the details of a new document in the User Model. I suggest the data is stored in a different way: Taking it as key-value pairs. But by doing that fix we need to export UserSchema from User.js so that we can use the function generateHash. I shall attach the different possible fixes for this issue.

**Comment by adityavinodk** [comment]
<img width="745" alt="screen shot 2018-06-28 at 10 28 20 pm" src="https://user-images.githubusercontent.com/32671846/42049267-16d198ec-7b23-11e8-84b6-69247ebfa970.png">

**Comment by adityavinodk** [comment]
We must export both User and UserSchema from User.js to facilitate this. In admin.js we require both User and UserSchema

**Comment by aniketnk** [comment]
This will be resolved once the front end account management is done. Don't export the generate hash function, you can just hash the password outside initialization.

**Comment by aniketnk** [comment]
This also doesn't handle the case when the values aren't passed. It'll assign them to undefined, which is not correct. It should take it's default value.
