### ISSUE TITLE
Invalid Login not handled in front end.

### ISSUE THREAD

**Issue by aniketnk** [aniketnk/alcoding-data-analysis#46]

**Comment by aniketnk** [comment]
No error message pops up on wrong credentials.

**Comment by parthvshah** [comment]
@RRK1000 Was working on this.

**Comment by RRK1000** [comment]
An alert is shown on invalid login, will send a PR. Without a USN and Password input, the browser console should respond back with 'USN can't be empty', but it doesn't. I was trying figure that out.

**Comment by parthvshah** [comment]
Make sure it spans or alerts error. Something like this. Even a text below the box is fine.
![capture](https://user-images.githubusercontent.com/17783671/42309582-9e9b468c-8056-11e8-8544-2e86bc7903e4.JPG)
