### ISSUE TITLE
Assignment Upload currently Async with Post Request

### ISSUE THREAD

**Issue by adityavinodk** [aniketnk/alcoding-data-analysis#57]
Currently the Assignment Upload happens using the File Upload middleware which runs Async with the Post Request for any upload. The issue with that is that the file is uploaded to the server and the Files DB is updated and then the conditions for correct assignment upload are checked. Possible Solution - Figure a way to effectively have the callback function from the middleware after the conditions are met.

**Comment by aniketnk** [comment]
Replace this line 
app.post('/api/admin/upload', upload.single(keyName), requireRole("admin"), fileUpload ,function (req, res)
with
app.post('/api/admin/upload', requireRole("admin"), upload.single(keyName) fileUpload ,function (req, res)

**Comment by adityavinodk** [comment]
The suggestion you have given is understandable and useful for batch sign up by the admin, the issue here is to do with the assignments upload. In that we need to have the callback function of fileUpload after the callback function for checking the conditions for upload. Currently fix is being worked on for that.
