### ISSUE TITLE
New Assignments not shown properly 

### ISSUE THREAD

**Issue by adityavinodk** [aniketnk/alcoding-data-analysis#72]
Under the assignments tab, it is supposed to show the assignments that a student hasn't submitted. Currently if a student has yet to submit an assignment but another student already submitted that same assignment, at the bottom of this card, it is shown as 'Assignment Submitted!'. Although the user hasn't submitted, it is showing otherwise because some other user submitted this assignment. 
@RRK1000 Please look into this.

**Comment by RRK1000** [comment]
Issue fixed.
